# Generated by Django 6.0.2 on 2026-02-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MITSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bible', 'Bible'), ('guitar', 'Guitar'), ('work_skill', 'Work/Skill')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('planned_minutes', models.PositiveIntegerField()),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mits', to='core.dailycheckin')),
            ],
            options={
                'ordering': ['daily_checkin__date', 'category'],
            },
        ),
    ]
