# Generated by Django 6.0.2 on 2026-02-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_mitsession_miss_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitsession',
            options={'ordering': ['daily_checkin__date', 'skill__name', 'title']},
        ),
        migrations.AddField(
            model_name='skill',
            name='goal_minutes',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='mitsession',
            name='category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
