# Generated by Django 6.0.2 on 2026-02-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailycheckin_owner_skill_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitsession',
            name='planned_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mitsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
