# Generated by Django 6.0.2 on 2026-02-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mitsession_planned_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='goal_minutes',
            new_name='weekly_goal_minutes',
        ),
    ]
